# Author: K. Potamianos <karolos.potamianos@cern.ch>

image: python:latest

before_script:
  - python --version ; pip --version
  - pip install jsonschema

json_validation:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - git diff --name-only origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} | grep '\.json$' | xargs python3 json_validator.py
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0

